require('basic')
require('plugins')
require('plugin-config.colorscheme')
require('plugin-config.lualine')
require('plugin-config.autosession')
require('plugin-config.bufferline')
require('plugin-config.lspsaga')
require('lsp.setup')
require('lsp.cmp')
require('keybindings')
-- 快捷键实现
require('plugin-config.diagnostic_underline')
require('plugin-config.tab_switch')
