require('basic')
require('plugins')
require('plugin-config.colorscheme')
require('plugin-config.lualine')
require('plugin-config.autosession')
require('lsp.setup')
require('lsp.cmp')
require('keybindings')
